name: Build and Push SHIR Docker Image

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: chat9a0eacr.azurecr.io
  IMAGE_NAME: shir
  TAG: v3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login (AZURE OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Log in to Azure Container Registry (OIDC CLI)
        run: |
          az acr login --name ${{ env.REGISTRY }}

      
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}" >> $GITHUB_ENV

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          file: Dockerfile
          platforms: windows/amd64