name: Build and Push SHIR Docker Image

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: chat9a0eacr.azurecr.io
  IMAGE_NAME: shir
  TAG: v3

jobs:
  build-and-push:
    runs-on: windows-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Switch to Windows containers
        shell: pwsh
        run: |
          # This flips Docker Desktop to Windows container mode
          & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon windows

      - name: Azure Login (AZURE OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Log in to ACR
        shell: pwsh
        run: az acr login --name ${{ env.REGISTRY }}

      - name: Build Windows container
        shell: pwsh
        run: |
          docker build --platform windows/amd64 `
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} `
            -f Dockerfile .

      - name: Push to ACR
        shell: pwsh
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
